<?php
/**
 * @var $block \Overdose\Laybuy\Block\Catalog\Installments
 */
?>
<?php if ($block->canShow() && $block->showIn('cart')) : ?>
    <div class="laybuy-installments laybuy-installments-amount"><span class="installments-amount"><?php echo __('or 6 interest-free payments of <strong>%1</strong> with', $block->getCartInstallmentAmount())?></span>
        <img src="<?php echo $block->getLogo(); ?>"/>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Catalog/js/price-utils'
            ],
            function(
                $,
                utils
            ) {
                $(document).on('updatePrice', function(e){
                    e.target.innerText.match(/[0-9 , \.]+/g).some(function(el) {
                        let val;
                        if(val = parseFloat(el.replace(',', ''))) {
                            $('.laybuy-installments-amount span.installments-amount').html('or 6 interest free payments of <strong>'+ utils.formatPrice(val/6, {}) +'</strong> with');
                            return;
                        }
                    });
                });
            }
        );
    </script>
<?php endif; ?>
