<?php
/**
 * @var $block \Overdose\Laybuy\Block\Catalog\Installments
 */
?>
<?php if ($block->canShow() && $block->showIn('category')) : ?>
	<div style="display:none;">
	    <div class="laybuy-installments laybuy-installments-amount"><span class="installments-amount"></span>
	        <img src="<?php echo $block->getLogo(); ?>"/>
	        <a class="laybuy-modal-popup-trigger" href="#"><span class="icon icon-info"></span></a>
	    </div>
	</div>
    <div id="laybuy-modal-popup">
        <div class="laybuy-content-wrapper">
            <iframe src="<?php echo $block->getPopUpUrl(); ?>"></iframe>
        </div>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Catalog/js/price-utils',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                utils,
                modal
            ) {

            	var laybuy = $('.laybuy-installments.laybuy-installments-amount').clone();
            	$('.price-box').append(laybuy);

            	$('.price-box').each(function(){
            		var price = $('.price-wrapper',this).data('price-amount');
            		$('.laybuy-installments-amount span.installments-amount',this).html('or 6 interest free payments of <strong>'+ utils.formatPrice(price/6, {decimalSymbol:'.'}) +'</strong> with');
            	});

                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: false,
                    clickableOverlay: true,
                    modalClass: 'laybuy-learn-more',
                    buttons: []
                };

                var popup = modal(options, $('#laybuy-modal-popup'));

                $( ".laybuy-modal-popup-trigger" ).on( "click", function() {
                    $('#laybuy-modal-popup').modal('openModal');
                });
            }
        );
    </script>
<?php endif; ?>