<?php
/**
 * @var $block \Overdose\Laybuy\Block\Catalog\Installments
 */
?>
<?php if ($block->canShow() && $block->showIn('product')) :?>
    <?php if($block->getType() != 'grouped'): ?>
    <div class="laybuy-installments laybuy-installments-amount" <?php if($block->getType() == 'bundle'): echo 'style="display:none;"'; endif; ?>>
        <?php if($block->getType() != 'bundle'): ?>
            <span class="installments-amount"><?php echo __('or 6 interest-free payments of <strong>%1</strong>', $block->getInstallmentsAmount())?></span>
        <?php else: ?>
            <span class="installments-amount"><?php echo __('or 6 interest-free payments of <strong>%1</strong>', $block->getInstallmentCurrency().number_format($block->getProductPrice()[0] / 6, 2).' - '.$block->getInstallmentCurrency().number_format($block->getProductPrice()[1] / 6, 2))?></span>
        <?php endif; ?>
        <img src="<?php echo $block->getLogo(); ?>"/>
        <a href="https://popup.laybuy.com" onclick="return !window.open(this.href, 'Laybuy', 'width=405,height=620')"
           target="_blank">Learn more</a>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Catalog/js/price-utils'
            ],
            function(
                $,
                utils
            ) {
                <?php if($block->getType() == 'bundle'): ?>
                    var laybuy = $('.laybuy-installments.laybuy-installments-amount').clone().attr('style', '');
                    $('.product-info-price').after(laybuy);
                <?php endif; ?>

                var currency = '<?php echo $block->getInstallmentCurrency(); ?>';
                $(document).on('updatePrice', function(e){
                    var priceBoxEl = e.target;
                    $(e.target).parents().each(function(a,b) {
                        if($(b).hasClass('product-info-main')) {
                            var product = document.getElementById('product-price-'+$(priceBoxEl).data('product-id'));
                            product.innerText.match(/[0-9 , \.]+/g).some(function(el) {
                                let val;
                                val = parseFloat(el.replace(',', ''));
                                if(val) {
                                    $('.laybuy-installments-amount span.installments-amount strong').html(utils.formatPrice(val/6, {}))
                                }

                                if(val == 0){
                                    $('.laybuy-installments-amount span.installments-amount strong').html(currency+'0.00');
                                }
                            });
                        }
                    })
                });
            }
        );
    </script>
    <?php else: ?>
        <div style="display:none;">
            <div class="laybuy-installments laybuy-installments-amount"><span class="installments-amount"></span>
                <img src="<?php echo $block->getLogo(); ?>"/>
            </div>
        </div>
        <script>
        require(
            [
                'jquery',
                'Magento_Catalog/js/price-utils'
            ],
            function(
                $,
                utils
            ) {

                var priceBoxes = $('.table-wrapper.grouped .price-box.price-final_price');

                var laybuy = $('.laybuy-installments.laybuy-installments-amount').clone();
                priceBoxes.append(laybuy);

                priceBoxes.each(function(){
                    var element = this;
                    var product_id = $(element).data('product-id');
                    var product = document.getElementById('product-price-'+product_id);
                    product.innerText.match(/[0-9 , \.]+/g).some(function(el) {
                        let val;
                        console.log(val = parseFloat(el.replace(',', '')));
                        if(val = parseFloat(el.replace(',', ''))) {
                            $('.laybuy-installments-amount span.installments-amount',element).html('or 6 interest free payments of <strong>'+utils.formatPrice(val/6, {decimalSymbol:'.'})+'</strong> with ');
                        }
                    });
                });
            }
        );
    </script>
    <?php endif; ?>
<?php endif; ?>
