<?php
/**
 * @var $block \Overdose\Laybuy\Block\Catalog\Installments
 */
?>
<?php if ($block->canShow() && $block->showIn('product')) : ?>
    <div class="laybuy-installments laybuy-installments-amount"><span class="installments-amount"><?php echo __('or 6 interest-free payments of <strong>%1</strong> with', $block->getInstallmentsAmount())?></span>
        <img src="<?php echo $block->getLogo(); ?>"/>
        <a class="laybuy-modal-popup-trigger" href="#"><span class="icon icon-info"></span></a>
    </div>
    <div id="laybuy-modal-popup">
        <div class="laybuy-content-wrapper">
            <iframe src="<?php echo $block->getPopUpUrl(); ?>"></iframe>
        </div>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Catalog/js/price-utils',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                utils,
                modal
            ) {
                
                $(document).on('updatePrice', function(e){
                    var priceBoxEl = e.target;
                    $(e.target).parents().each(function(a,b) {
                        if($(b).hasClass('product-info-main')) {
                            var product = document.getElementById('product-price-'+$(priceBoxEl).data('product-id'));
                            product.innerText.match(/[0-9 , \.]+/g).some(function(el) {
                                let val;
                                if(val = parseFloat(el.replace(',', ''))) {
                                    $('.laybuy-installments-amount span.installments-amount strong').html(utils.formatPrice(val/6, {}))
                                    return;
                                }})
                        }
                    })
                });


                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: false,
                    clickableOverlay: true,
                    modalClass: 'laybuy-learn-more',
                    buttons: []
                };

                var popup = modal(options, $('#laybuy-modal-popup'));

                $( ".laybuy-modal-popup-trigger" ).on( "click", function() {
                    $('#laybuy-modal-popup').modal('openModal');
                });
            }
        );
    </script>
<?php endif; ?>