<?php
/**
 * @var $block \Laybuy\Laybuy\Block\Info
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle())?>

<?php if ($_specificInfo = $block->getSpecificInformation()):?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <?php if(strtotime($_label)):?>
                <tr>
                    <td colspan="3"><?php echo $block->escapeHtml($_label)?>:</td>
                </tr>

                <?php foreach ($_value as $_subKey => $_subValue):?>
                    <tr>
                        <td></td>
                        <td><?php echo $block->escapeHtml($_subKey)?>:</td>
                        <td><?php echo nl2br(implode($block->getValueAsArray($_subValue, true), "\n"))?></td>
                    </tr>
                <?php endforeach; ?>

            <?php else: ?>
                <tr>
                    <td><?php echo $block->escapeHtml($_label)?>:</td>
                    <td colspan="2"><?php echo nl2br(implode($block->getValueAsArray($_value, true), "\n"))?></td>
                </tr>
            <?php endif;?>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $block->getChildHtml()?>